### PR TITLE
Add 3.11-dev support

### PR DESCRIPTION
**Pull request by FasterSpeeding**
### Summary
Add 3.11 support

### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [x] I have made unittests according to the code I have added/modified/deleted.

### CODE REVIEW

**Comment by FasterSpeeding** [comment]
> maybe worth opening an issue there

And will do

**Comment by davfsa** [comment]
Waiting on https://github.com/warner/python-ed25519/pull/16

**Comment by davfsa** [comment]
We might have to setup a fork for python-ed25519, as it doesn't look like the PR is getting merged any time soon unfortunately

**Comment by davfsa** [comment]
`ed25519` dependency removed by #986, unblocking this pr and hopefully can be merged after a rebase

**Comment by davfsa** [comment]
For some context on the tests breaking, this is due to aiohttp not using the latest cython version, which fixes those bugs. We will have to wait for the next release then

Relevant PR: https://github.com/aio-libs/aiohttp/pull/6396

**Comment by FasterSpeeding** [comment]
> For some context on the tests breaking, this is due to aiohttp and yarl not using the latest cython version, which fixes those bugs. We will have to wait for the next release then
> 
> Relevant PRs: [aio-libs/aiohttp#6396](https://github.com/aio-libs/aiohttp/pull/6396) and [aio-libs/yarl#654](https://github.com/aio-libs/yarl/pull/654)

I'm aware, I'm just messing around with stuff to see if i can get it to run in the pipelines by just installing from source to see if anything does break cause i'm bored (but this has turned into too much effort so given up on the idea)

**Comment by davfsa** [comment]
> I'm aware, I'm just messing around with stuff to see if i can get it to run in the pipelines by just installing from source to see if anything does break cause i'm bored (but this has turned into too much effort so given up on the idea)

Was just leaving it for prosperity :P

**Comment by UnknownLITE** [comment]
**Python 3.11.0b4 is now available**, and
[Python.org strongly encourage maintainers of third-party Python projects to test with 3.11 during the beta phase and report issues found to the Python bug tracker as soon as possible](https://pythoninsider.blogspot.com/2022/07/python-3110b4-is-now-available.html)

**Comment by davfsa** [comment]
> **Python 3.11.0b4 is now available**, and
> [Python.org strongly encourage maintainers of third-party Python projects to test with 3.11 during the beta phase and report issues found to the Python bug tracker as soon as possible](https://pythoninsider.blogspot.com/2022/07/python-3110b4-is-now-available.html)
> 
> Maybe it is irrelevant for this project idk
> 

We have been trying to test CPython 3.11 for some time now (reason for this pr), but the dependencies of hikari don't support 3.11 yet, so we can't

**Comment by davfsa** [comment]
Just re-triggering CI

**Comment by davfsa** [comment]
cchardet was dropped as a speedup for aiohttp (< python 3.10) in this version too due to it being unmaintained.

There have been talks about a replacement, but no outcome yet. Best bet would be to just install `aiohttp[speedups]~=same version as requirements` to prevent this from happening in the future.

The links for speedups should also have to be updated to just point to the aiohttp docs to see what packages are being installed on top

**Review by davfsa — APPROVED** [review]

**Pull request merged**
