### PR TITLE
Remove field validation from `serialize_embed`

### PR DESCRIPTION
**Pull request by davfsa**
This validation only checks fields and not all the other possibilities that Discord will complain about. It is best to just leave it to Discord to decide whether to error or not.

### CODE REVIEW

**Comment by FasterSpeeding** [comment]
You won't get an error response from discord in the interaction server flow

**Comment by davfsa** [comment]
> You won't get an error response from discord in the interaction server flow, could move this logic to the response builders instead maybe? 

I personally dislike builders a tiny bit because, for other languages it would be great, but for python it just adds overhead, so I really don't know.

Maybe it could be added there but, and I havent played around with an interaction server yet so idk, if Discord don't reply with error codes, handing this one specific case for embeds and not all the other things Discord could raise I as a bit unnecessary. We might as well not handle anything and skip all these checks all the time.

**Comment by FasterSpeeding** [comment]
> I personally dislike builders a tiny bit because, for other languages it would be great, but for python it just adds overhead, so I really don't know.

Adds overhead compared to what?

> Maybe it could be added there but, and I havent played around with an interaction server yet so idk, if Discord don't reply with error codes, handing this one specific case for embeds and not all the other things Discord could raise I as a bit unnecessary. We might as well not handle anything and skip all these checks all the time, as it would be more in-line with the rest of the lib, don't you think?

It being more inline with the rest of the lib would be bad ux there; the plan has always been to add some level of validation to the server response builders as you don't get a response to your initial response and therefore will get no info/feedback on why it failed (just this is really low priority).

**Comment by davfsa** [comment]
> Adds overhead compared to what?

Sorry, wrote that as I woke up and idk what I was thinking. Embed is basically a builder anyways, so yea, the validation could be moved there

> It being more inline with the rest of the lib would be bad ux there; the plan has always been to add some level of validation to the server response builders as you don't get a response to your initial response and therefore will get no info/feedback on why it failed (just this is really low priority). 

Yea, there it would make sense there. My bad

**Pull request closed without merging**
