### PR TITLE
Remove Tanjun from README.md

### PR DESCRIPTION
**Pull request by FasterSpeeding**
It's just wasting space there and shouldn't be there

### Checklist

- [ ] I have run `nox` and all the pipelines have passed.
- [ ] I have made unittests according to the code I have added/modified/deleted.

### CODE REVIEW

**Comment by AlexanderHOtt** [comment]
I still use tanjun, so I see no reason to remove it if there is still a userbase.

**Comment by GoogleGenius** [comment]
I am also actively developing and dependent on the Tanjun framework. Please reconsider this.

**Comment by thesadru** [comment]
Tanjun is essential to the Hikari ecosystem. Lightbulb targets a completely different demographic.

**Review by davfsa — APPROVED** [review]
Considering it looks like you are still updating Tanjun, all I can do is ask for you keep it there. It takes absolutely no place, since its just a text file. There is nothing better that could be replacing it.

But then again, this is not my place to talk. All I can do is ask for you to keep it there. But if you want to remove it, its you lib, your call

I would love for it to stay :)

**Pull request closed without merging**
