### PR TITLE
Do not send "embeds" in message create payloads when not specified

### PR DESCRIPTION
**Pull request by davfsa**
### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [x] I have made unittests according to the code I have added/modified/deleted.

### CODE REVIEW

**Comment by FasterSpeeding** [comment]
Are you going to handle all the other cases where empty values could be sent in create endpoints as well?

**Comment by davfsa** [comment]
> Are you going to handle all the other cases where empty values could be sent in create endpoints as well?

If any of those are created by us if the user didn't specify anything, yes. But I haven't seen any like that.

**Comment by FasterSpeeding** [comment]
> > Are you going to handle all the other cases where empty values could be sent in create endpoints as well?
> 
> If any of those are created by us if the user didn't specify anything, yes. But I haven't seen any like that.

Why does this matter anyway

**Comment by davfsa** [comment]
> Why does this matter anyway

Not sending unnecessary information when we don't have to

**Comment by FasterSpeeding** [comment]
> > Why does this matter anyway
> 
> Not sending unnecessary information when we don't have to
> 

Then shouldn't you also add in checks for when the user specified an empty value to avoid sending unnecessary information to other endpoints

**Review by FasterSpeeding — APPROVED** [review]

**Pull request merged**
