### PR TITLE
Add `start_function` argument to `GatewayBot.start()`

### PR DESCRIPTION
**Pull request by AlexanderHOtt**
### Summary

Add an option to use a given `start` function to start the bot, also fix a typo in docs.

This will be a long one.

Heres a simple Bot class that inherits from `hikari.GatewayBot`

```py
# bot.py

class Bot(hiakri.GatewayBot):

    def __init__(self):

        super().__init__(
            token="token",
            intents=hikari.Intents.ALL
        )

    async def start(
        self,
        *,
        activity = None,
        afk = False,
        check_for_updates = True,
        idle_since = None,
        ignore_session_start_limit = False,
        large_threshold = 250,
        shard_ids = None,
        shard_count = None,
        status,
    ):
        self.do_stuff()

        await super().start(
            activity=activity,
            afk=afk,
            check_for_updates=check_for_updates,
            idle_since=idle_since,
            ignore_session_start_limit=ignore_session_start_limit,
            large_threshold=large_threshold,
            shard_ids=shard_ids,
            shard_count=shard_count,
            status=status,
        )

    def run(
        self,
        *,
        activity = None,
        afk = False,
        asyncio_debug = None,
        check_for_updates = True,
        close_passed_executor = False,
        close_loop = True,
        coroutine_tracking_depth = None,
        enable_signal_handlers = True,
        idle_since = None,
        ignore_session_start_limit = False,
        large_threshold = 250,
        propagate_interrupts = False,
        status,
        shard_ids = None,
        shard_count = None,
    ):
        self.do_stuff()

        super().run(
            activity=activity,
            afk=afk,
            asyncio_debug=asyncio_debug,
            check_for_updates=check_for_updates,
            close_passed_executor=close_passed_executor,
            close_loop=close_loop,
            coroutine_tracking_depth=coroutine_tracking_depth,
            enable_signal_handlers=enable_signal_handlers,
            idle_since=idle_since,
            ignore_session_start_limit=ignore_session_start_limit,
            large_threshold=large_threshold,
            propagate_interrupts=propagate_interrupts,
            status=status,
            shard_ids=shard_ids,
            shard_count=shard_count,
        )

    def do_stuff():
        pass
```

Heres a sample \_\_main\_\_.py file with two different main methods that I want to switch between from time to time.
```py
# __main__.py

bot = Bot()

def main_1():

    # `foo` is some async app (like an api)    
    @foo.starting_event
    def app_starting_event():
        bot.start()

    @foo.stopping_event
    def app_stopping_event():
        bot.close()
    
    foo.run()

def main_2()
    bot.run()

if __name__ == "__main__":
    # main_1()
    main_2()

```

When running `main_2()` there is an unexpected function order that the bot calls: `bot.run()` -> `GatewayBot.run()` -> `bot.start()` -> `GatewayBot.start()`. It is strange that `GatewayBot.run()` calles `bot.start()`, but I figured out why.

Inside of `GatewayBot.run()` it runs

```py
# inside of `GatewayBot.run()`
loop.run_until_complete(
    self.start(
        activity=activity,
        afk=afk,
        check_for_updates=check_for_updates,
        idle_since=idle_since,
        ignore_session_start_limit=ignore_session_start_limit,
        large_threshold=large_threshold,
        shard_ids=shard_ids,
        shard_count=shard_count,
        status=status,
    )
)
```

With inheritence, `self` (inside of `loop.run_until_complete()`) is the `Bot` class, not the `GatewayBot` class. So `bot.start()` is called, not `GatewayBot.start()`.
I thought this could fixed by adding a `use_parrent_start` parameter to `GatewayBot.run()` but it can't. Here's the code anyway.
```py
# new `GatewayBot.run()` method

def run(
    self,
    *,
    activity = None,
    afk = False,
    asyncio_debug = None,
    check_for_updates = True,
    close_passed_executor = False,
    close_loop = True,
    coroutine_tracking_depth = None,
    enable_signal_handlers = True,
    idle_since = None,
    ignore_session_start_limit = False,
    large_threshold = 250,
    propagate_interrupts = False,
    status,
    shard_ids = None,
    shard_count = None,
    use_parrent_start = False,
):
    # ...
    if use_parrent_start:
        loop.run_until_complete(
            super().start(
                activity=activity,
                afk=afk,
                check_for_updates=check_for_updates,
                idle_since=idle_since,
                ignore_session_start_limit=ignore_session_start_limit,
                large_threshold=large_threshold,
                shard_ids=shard_ids,
                shard_count=shard_count,
                status=status,
            )
        )
    else:
        loop.run_until_complete(
            self.start(
                activity=activity,
                afk=afk,
                check_for_updates=check_for_updates,
                idle_since=idle_since,
                ignore_session_start_limit=ignore_session_start_limit,
                large_threshold=large_threshold,
                shard_ids=shard_ids,
                shard_count=shard_count,
                status=status,
            )
        )
    # ...
```
For some reason, this didn't work, (maybe I'm just bad and it does). This would be the more elegant way to implement it though, but again, it didn't work, so I added a `use_start_function` parameter to `GatewayBot.run()` instead.

```py
# new `GatewayBot.run()` method

def run(
    self,
    *,
    activity = None,
    afk = False,
    asyncio_debug = None,
    check_for_updates = True,
    close_passed_executor = False,
    close_loop = True,
    coroutine_tracking_depth = None,
    enable_signal_handlers = True,
    idle_since = None,
    ignore_session_start_limit = False,
    large_threshold = 250,
    propagate_interrupts = False,
    status,
    shard_ids = None,
    shard_count = None,
    start_function = None,
):
    # ...
    if start_function is not None:
        loop.run_until_complete(
            start_function(
                activity=activity,
                afk=afk,
                check_for_updates=check_for_updates,
                idle_since=idle_since,
                ignore_session_start_limit=ignore_session_start_limit,
                large_threshold=large_threshold,
                shard_ids=shard_ids,
                shard_count=shard_count,
                status=status,
            )
        )
    else:
        loop.run_until_complete(
            self.start(
                activity=activity,
                afk=afk,
                check_for_updates=check_for_updates,
                idle_since=idle_since,
                ignore_session_start_limit=ignore_session_start_limit,
                large_threshold=large_threshold,
                shard_ids=shard_ids,
                shard_count=shard_count,
                status=status,
            )
        )
    # ...
```

```py
# new bot.run() method
# ...
super().run(
    activity=activity,
    afk=afk,
    asyncio_debug=asyncio_debug,
    check_for_updates=check_for_updates,
    close_passed_executor=close_passed_executor,
    close_loop=close_loop,
    coroutine_tracking_depth=coroutine_tracking_depth,
    enable_signal_handlers=enable_signal_handlers,
    idle_since=idle_since,
    ignore_session_start_limit=ignore_session_start_limit,
    large_threshold=large_threshold,
    propagate_interrupts=propagate_interrupts,
    status=status,
    shard_ids=shard_ids,
    shard_count=shard_count,
    start_function=super().start
    )
# ...
```

This worked, but I don't know if theres a good way to check if the given method will actually work, or if it has the same signature as `GatewayBot.start()`. 

### Checklist

- [x] I have run `nox` and all the pipelines have passed. (flake8 still complained about no shebang line)
- [ ] I have made unittests according to the code I have added/modified/deleted.
  - I'm not sure what tests to write

### CODE REVIEW

**Comment by norinorin** [comment]
Isn't this what lifetime events are for or am I missing something?

**Comment by crazygmr101** [comment]
Why not just subclass at this point tho?

**Comment by davfsa** [comment]
Personally, I would rather go with inheritance or lifetime events. I think we have that area quite well covered and I dont see a spot for this, sorry.

Thanks for taking the time to open the pull request tho. Will wait for @FasterSpeeding to comment, but I would personally say no to this for the reasons I mentioned above

**Comment by davfsa** [comment]
Going to close this as I dont see the need for it. You can directly subclass and add your own functionality if needed

**Pull request closed without merging**
