### PR TITLE
Small doc fixes around menu value ranges

### PR DESCRIPTION
**Pull request by FasterSpeeding**
### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [ ] I have made unittests according to the code I have added/modified/deleted.

### CODE REVIEW

**Comment by FasterSpeeding** [comment]
@davfsa you should prob be using the relevant auto-formatting stuff on stuff like the change log and contributing guidelines

**Comment by davfsa** [comment]
> @davfsa you should prob be checking that the relevant auto-formatting stuff has actually been run on stuff like the change log and contributing guidelines

Opened #793 for that :+1:

**Review by davfsa — APPROVED** [review]
Should we add a changelog fragment?

**Comment by FasterSpeeding** [comment]
Small doc fixes don't need to be included in changelogs

**Pull request merged**
