### PR TITLE
Deprecate CacheView.iterator in favour of using itertools

### PR DESCRIPTION
**Pull request by davfsa**
### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [x] I have made unittests according to the code I have added/modified/deleted.

### CODE REVIEW

**Comment by FasterSpeeding** [comment]
I mean this is still helpful by itself: its more ergonomic if you want to do an async operation over the entries in a cache using an async iterator and collect/iterate over the results rather than directly building an impl of them but it isn't necessary and is arguably misleading so I don't mind getting rid of it.

**Comment by FasterSpeeding** [comment]
I mean this is still helpful by itself: its more ergonomic if you want to do an async operation over the entries in a cache using an async iterator and collect/iterate over the results rather than directly building an impl of them but it isn't necessary and is arguably misleading so I don't mind getting rid of it.

**Review by FasterSpeeding — APPROVED** [review]

**Comment by davfsa** [comment]
That is the idea behind it. In async cache views, the iterator can still be added if needed :)

**Comment by FasterSpeeding** [comment]
> That is the idea behind it. In async cache views, the iterator can still be added if needed :)

Fine by me then

**Pull request merged**
