### PR TITLE
Add thread channel support for `get_channel` and `fetch_channel` methods

### PR DESCRIPTION
**Pull request by Lunarmagpie**
### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [ ] I have made unittests according to the code I have added/modified/deleted.

### CODE REVIEW

**Comment by davfsa** [comment]
Tests are failing, please have a look and fix them :)

**Comment by Lunarmagpie** [comment]
Sorry been busy. I'm going to fix that today.

**Comment by Lunarmagpie** [comment]
Hikari favors protocols over ABCs a lot of the time so I have changed the classes to look like this:
```python 
class Mixin(fast_protocol.FastProtocolChecking, typing.Protocol):
   # this is the same
   ...
```
If `ABC` is preferred here tell me and ill change it back.

Starting to question some stuff about the mixins to be honest. I think some of them use inheritance where the design pattern I have in this PR would be more optimal. If you guys want me to I can refactor that part of the library.

**Comment by Lunarmagpie** [comment]
Nobody has given me updated on what to do

**Pull request closed without merging**
