### PR TITLE
Fix deploy for the last time ever

### PR DESCRIPTION
**Pull request by davfsa**
### Summary
After this I am not going to do any changes to the deploy script ever again. I thought I had tested every line thoroughly and nothing was wrong. Turns out I forgot to escape a the `$` character, so no errors were being raised. Additionally I thought I copy pasted each line to avoid any issues, looks like I didnt.

After this I will just create a small release and yank `2.0.0.dev106`. Not much has changed since.

I am deeply sorry

### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [x] I have made unittests according to the code I have added/modified/deleted.

### CODE REVIEW

**Comment by FasterSpeeding** [comment]
> After this I will just create a small release and yank 2.0.0.dev106. Not much has changed since.

So `2.0.0.dev106.post1`?

**Comment by davfsa** [comment]
> > After this I will just create a small release and yank 2.0.0.dev106. Not much has changed since.
> 
> So a post release `2.0.0.dev106.post1`?

Could just be `2.0.0.dev107` tbh

**Comment by FasterSpeeding** [comment]
> > > After this I will just create a small release and yank 2.0.0.dev106. Not much has changed since.
> > 
> > 
> > So a post release `2.0.0.dev106.post1`?
> 
> Could just be `2.0.0.dev107` tbh

There's stuff scheduled for the next actual release though that isn't done yet

**Comment by davfsa** [comment]
> There's stuff scheduled for the next actual release though that isn't done yet

That could just be pushed to `2.0.0.dev108`. These are development versions after all. I dont think it matters much

**Review by FasterSpeeding — APPROVED** [review]

**Pull request merged**
