### PR TITLE
Document more newly documented rest codes

### PR DESCRIPTION
**Pull request by davfsa**

### CODE REVIEW

**Comment by FasterSpeeding** [comment]
Legit question though what is the point of this enum? It doesn't document which endpoints return what codes and it doesn't cover anywhere near all of the error rest codes and what is the use case for matching error rest codes

**Comment by davfsa** [comment]
> Legit question though what is the point of this enum? It doesn't document which endpoints return what codes and it doesn't cover anywhere near all of the error rest codes and what is the use case for matching error rest codes

It may very well be removed tbh, it is only used to provide a bit more info on rest errors, but ig we can just have the int and forget about it

**Comment by FasterSpeeding** [comment]
> it is only used to provide a bit more info on rest errors

Here's the thing about that, the message for these codes is just in the error payload so if you want a more user friendly way to present the error then just do `error.message` for something to show to a user

**Comment by davfsa** [comment]
Will play around with this and open a followup pr that removes the enum

**Pull request closed without merging**
