### PR TITLE
Add a member object return to rest.edit_member

### PR DESCRIPTION
**Pull request by FasterSpeeding**
### Summary
Add a member object return to rest.edit_member

### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [x] I have made unittests according to the code I have added/modified/deleted.

### CODE REVIEW

**Comment by davfsa** [comment]
Docs state that this returns a 204 on success, has this been changed not documented?

**Comment by FasterSpeeding** [comment]
> Docs state that this returns a 204 on success, has this been changed not documented?
> 
> https://discord.com/developers/docs/resources/guild#modify-guild-member

that's a undocumented V8 change

**Comment by FasterSpeeding** [comment]
Might or might not bother to open a pr to change the docs:tm:

**Comment by davfsa** [comment]
Created #2505 to address this

**Comment by FasterSpeeding** [comment]
> Created [discord/discord-api-docs#2505](https://github.com/discord/discord-api-docs/pull/2505) to address this

To address what?

**Review by davfsa — APPROVED** [review]

**Pull request merged**
