### PR TITLE
chore: update Discord API version in README

### PR DESCRIPTION
**Pull request by thenishantsapkota**
### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [x] I have made unittests according to the code I have added/modified/deleted.

### CODE REVIEW

**Comment by davfsa** [comment]
It completely flew over my head to check for this. Iirc, there should be another v9 lying around (think it's in `shard.py`). Mind fixing that one too?

Ty for the pr tho!

**Comment by novanai** [comment]
There's 2 instances of `V8` in `hikari.impl.shard`, 2 in `hikari.impl.rest` and 1 in `hikari.api.shard` too btw :P

**Comment by thenishantsapkota** [comment]
I couldn't find any instances of `v9` anywhere.
Are you sure it exists?
Please confirm.

**Comment by davfsa** [comment]
Think those are all. I believe they were just never updated from v8 to v9. Thanks for taking the time to do this!

**Review by davfsa — APPROVED** [review]

**Comment by thenishantsapkota** [comment]
> Think those are all. I believe they were just never updated from v8 to v9. Thanks for taking the time to do this!

:bow:

**Pull request merged**
