### PR TITLE
Switch python3.10 to dev version

### PR DESCRIPTION
**Pull request by davfsa**
### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [x] I have made unittests according to the code I have added/modified/deleted.

### CODE REVIEW

**Comment by FasterSpeeding** [comment]
The tests just aren't gonna run until https://github.com/python/typed_ast/pull/155 if we bump to 3.10.0-apha6 or above, is that really what we want?

**Comment by davfsa** [comment]
> The tests just aren't gonna run until https://github.com/python/typed_ast/pull/155 if we bump to 3.10.0-apha6 or above, is that really what we want?

That bug got fixed on master and could be fixed at any time, which is why I would have this one merged so we can just have pipelines running to try and pass on 3.10

**Comment by FasterSpeeding** [comment]
> > The tests just aren't gonna run until [python/typed_ast#155](https://github.com/python/typed_ast/pull/155) if we bump to 3.10.0-apha6 or above, is that really what we want?
> 
> That bug got fixed on master and could be fixed at any time, which is why I would have this one merged so we can just have pipelines running to try and pass on 3.10

Could we just temporarily target a specific commit on their master until they release the change?

**Comment by davfsa** [comment]
https://github.com/aio-libs/aiohttp/issues/5604

I'm thinking on just not installing `aiodns` on Python3.10. @FasterSpeeding opinions?

**Comment by FasterSpeeding** [comment]
Would it be worth it opening an issue here to track aiodns on 3.10 even if it ends up being a long hanging one just so we dont forget about it?

**Pull request merged**
