### PR TITLE
Document new 20031 error code

### PR DESCRIPTION
**Pull request by davfsa**
### Checklist

- [x] I have run `nox` and all the pipelines have passed.
- [x] I have made unittests according to the code I have added/modified/deleted.

### CODE REVIEW

**Comment by FasterSpeeding** [comment]
The docstring for this class should mention that it's non-exhaustive

**Comment by davfsa** [comment]
> 
> 
> The docstring for this class should mention that it's non-exhaustive

Wdym?

**Comment by FasterSpeeding** [comment]
> > The docstring for this class should mention that it's non-exhaustive
> 
> Wdym?

The RESTErrorCode enum is an non-exhaustive list (it doesn't cover all the error codes just like the list in the docs) and should be documented as such.

Also I don't think UNKNOWN_ERROR is relevant anymore since initialisation should just return a literal int if it doesn't find an enum member for the value so that should probably be removed at some point.

**Comment by davfsa** [comment]
> The RESTErrorCode enum is an non-exhaustive list (it doesn't cover all the error codes just like the list in the docs) and should be documented as such.

Yep, will add that.

> Also I don't think UNKNOWN_ERROR is relevant anymore since initialisation should just return a literal int if it doesn't find an enum member for the value so that should probably be removed at some point.

UNKNOWN_ERROR is an actual code, not just the default

**Comment by FasterSpeeding** [comment]
> UNKNOWN_ERROR is an actual code, not just the default

Are you thinking of the gateway close event error code? Json error codes never go negative as far as documented behaviour goes so not exactly sure `UNKNOWN_ERROR = -1` is an actual error code for rest json responses

**Comment by davfsa** [comment]
> Are you thinking of the gateway close event error code? Json error codes never go negative as far as documented behaviour goes so not exactly sure `UNKNOWN_ERROR = -1` is an actual error code for rest json responses (would've thought stuff would always default to 0 - General error - for json error responses)

Oh, true. Will remove

**Review by FasterSpeeding — APPROVED** [review]

**Pull request merged**
